[project]
name = "ravenhelper-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "async-lru>=2.1.0",
    "cachetools>=7.0.0",
    "docstring-parser>=0.17.0",
    "numerize>=0.12",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.46",
    "thefuzz>=0.22.1",
    "twitchio>=3.2.1",
    "websockets>=16.0",
]
