from ravenpy import Skills, ItemMaterials, Effects, Stat

skill_contractions = {
    Skills.Woodcutting: "Wood",
    Skills.Farming: "Farm",
    Skills.Crafting: "Craft",
    Skills.Cooking: "Cook",
    Skills.Fishing: "Fish",
    Skills.Alchemy: "Alch",
    Skills.Gathering: "Gather",
    Skills.Mining: "Mine",
    Skills.Health: "HP",
    Skills.Attack: "Atk",
    Skills.Defense: "Def",
    Skills.Strength: "Str",
    Skills.Magic: "Magic",
    Skills.Ranged: "Range",
    Skills.Healing: "Heal",
    Skills.Sailing: "Sail",
    Skills.Slayer: "Slay"
}
material_names = {
    ItemMaterials.Bronze: "Bronze",
    ItemMaterials.Iron: "Iron",
    ItemMaterials.Steel: "Steel",
    ItemMaterials.Black: "Black",
    ItemMaterials.Mithril: "Mithril",
    ItemMaterials.Adamantite: "Adamantite",
    ItemMaterials.Rune: "Rune",
    ItemMaterials.Dragon: "Dragon",
    ItemMaterials.Abraxas: "Abraxas",
    ItemMaterials.Phantom: "Phantom",
    ItemMaterials.Lionsbane: "Lionsbane",
    ItemMaterials.Ether: "Ether",
    ItemMaterials.Ancient: "Ancient",
    ItemMaterials.Atlarus: "Atlarus",
    ItemMaterials.ElderBronze: "Elder Bronze",
    ItemMaterials.ElderIron: "Elder Iron",
    ItemMaterials.ElderSteel: "Elder Steel",
    ItemMaterials.ElderBlack: "Elder Black",
    ItemMaterials.ElderMithril: "Elder Mithril",
    ItemMaterials.ElderAdamantite: "Elder Adamantite",
    ItemMaterials.ElderRune: "Elder Rune",
    ItemMaterials.ElderDragon: "Elder Dragon",
    ItemMaterials.ElderAbraxas: "Elder Abraxas",
    ItemMaterials.ElderPhantom: "Elder Phantom",
    ItemMaterials.ElderLionsbane: "Elder Lionsbane",
    ItemMaterials.ElderEther: "Elder Ether",
    ItemMaterials.ElderAncient: "Elder Ancient",
    ItemMaterials.ElderAtlarus: "Elder Atlarus",
}

status_effect_names = {
    Effects.NoEffect: "No effect",
    Effects.Heal: "HP",
    Effects.Regeneration: "Regeneration",
    Effects.Strength: "Strength",
    Effects.Defense: "Defense",
    Effects.Dodge: "Dodge",
    Effects.HitChance: "Hit chance",
    Effects.MovementSpeed: "Movement speed",
    Effects.AttackSpeed: "Attack speed",
    Effects.CastSpeed: "Cast speed",
    Effects.AttackPower: "Attack power",
    Effects.RangedPower: "Ranged power",
    Effects.MagicPower: "Magic power",
    Effects.HealingPower: "Healing power",
    Effects.ExperienceGain: "Experience gain",
    Effects.CriticalHitChance: "Critical hit chance",
    Effects.InflictPoison: "Inflict poison",
    Effects.InflictBleeding: "Inflict bleeding",
    Effects.Burning: "Burning",
    Effects.HealthSteal: "Health steal",
    Effects.Poison: "Poison",
    Effects.Bleeding: "Bleeding",
    Effects.Burning2: "Burning",
    Effects.Damage: "Damage",
    Effects.ReducedHitChance: "Reduced hit chance",
    Effects.ReducedMovementSpeed: "Reduced movement speed",
    Effects.ReducedAttackSpeed: "Reduced attack speed",
    Effects.ReducedCastSpeed: "Reduced cast speed",
    Effects.IncreasedCriticalHitDamage: "Increased crit. damage",
    Effects.RemoveItem: "Remove item",
    Effects.AddItem: "Add item",
    Effects.Teleport: "Teleport",
}
status_effect_names_short = {
    Effects.NoEffect: "None",
    Effects.Heal: "HP",
    Effects.Regeneration: "Regen",
    Effects.Strength: "Str",
    Effects.Defense: "Def",
    Effects.Dodge: "Dodge",
    Effects.HitChance: "Hit chance",
    Effects.MovementSpeed: "Speed",
    Effects.AttackSpeed: "Atk speed",
    Effects.CastSpeed: "Cast speed",
    Effects.AttackPower: "Atk power",
    Effects.RangedPower: "Ranged power",
    Effects.MagicPower: "Magic power",
    Effects.HealingPower: "Healing power",
    Effects.ExperienceGain: "EXP gain",
    Effects.CriticalHitChance: "Crit chance",
    Effects.InflictPoison: "Deal poison",
    Effects.InflictBleeding: "Deal bleeding",
    Effects.Burning: "Burn",
    Effects.HealthSteal: "HP steal",
    Effects.Poison: "Poison",
    Effects.Bleeding: "Bleed",
    Effects.Burning2: "Burn",
    Effects.Damage: "Dmg",
    Effects.ReducedHitChance: "Reduced hit chance",
    Effects.ReducedMovementSpeed: "Reduced speed",
    Effects.ReducedAttackSpeed: "Reduced attack",
    Effects.ReducedCastSpeed: "Reduced cast speed",
    Effects.IncreasedCriticalHitDamage: "Crit dmg",
    Effects.RemoveItem: "Remove item",
    Effects.AddItem: "Add item",
    Effects.Teleport: "Teleport",
}
stat_names = {
    Stat.WeaponAim: "Weapon aim",
    Stat.WeaponPower: "Weapon power",
    Stat.MagicAim: "Magic aim",
    Stat.MagicPower: "Magic power",
    Stat.RangedAim: "Ranged aim",
    Stat.RangedPower: "Ranged power",
    Stat.ArmorPower: "Armor power",
}

month_names = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
]
